import {ipcMain} from "electron";
import {spawn} from "child_process";
import os from "os";
import path from "path";
import fs from "fs/promises";
import {getSubtitles, getYoutubeVideoTitle} from "../../helpers/getSubtitles";
import {resolveToolCommand} from "./mediaTools";

export function registerYoutubeHandlers() {
  ipcMain.handle("getYoutubeSubtitleLanguages", async (event, videoID) => {
    console.log(`[IPC] getYoutubeSubtitleLanguages called for ${videoID}`);
    try {
      const ytDlpPath = await resolveToolCommand("yt-dlp");

      const ytDlpOutput = await new Promise<string>((resolve, reject) => {
        const child = spawn(ytDlpPath, [
          "--list-subs",
          "--write-auto-subs",
          `https://youtube.com/watch?v=${videoID}`
        ]);

        let stdout = "";
        let stderr = "";

        child.stdout.on("data", (data) => {
          stdout += data.toString();
        });

        child.stderr.on("data", (data) => {
          stderr += data.toString();
        });

        child.on("close", (code) => {
          if (code === 0) {
            resolve(stdout + stderr);
          } else {
            reject(new Error(`yt-dlp failed with code ${code}: ${stderr}`));
          }
        });

        child.on("error", (err) => {
          reject(new Error(`Failed to spawn yt-dlp: ${err.message}`));
        });
      });

      interface SubtitleLanguage {
        code: string;
        name: string;
        isAutoGenerated: boolean;
      }

      const languages: SubtitleLanguage[] = [];
      const lines = ytDlpOutput.split("\n");
      let currentSection = null;

      const displayNames = new Intl.DisplayNames(["en"], {type: "language"});

      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        const trimmedLine = line.trim();

        if (trimmedLine.includes("Available subtitles for")) {
          currentSection = "manual";
          continue;
        } else if (trimmedLine.includes("Available automatic captions for")) {
          currentSection = "auto";
          continue;
        }

        if (trimmedLine.includes("Language") && trimmedLine.includes("Name")) {
          continue;
        }

        if (!trimmedLine || trimmedLine.startsWith("[")) {
          if (languages.length > 0 && trimmedLine.startsWith("[")) {
            break;
          }
          continue;
        }

        if (currentSection && trimmedLine) {
          const langMatch = trimmedLine.match(/^([a-z]{2}(-[A-Za-z]+)?)\s+(.+)/);
          if (langMatch) {
            const langCode = langMatch[1];
            const langName = displayNames.of(langCode) || langCode.toUpperCase();

            const isAutoTranslated = langCode.includes("-zh") || langCode.includes("-ja") ||
              langCode.includes("-ko") || langCode.includes("-ar") ||
              langCode.includes("-hi") || langCode.includes("-es") ||
              langCode.includes("-fr") || langCode.includes("-de") ||
              langCode.includes("-ru") || langCode.includes("-pt") ||
              langCode.includes("-it") || langCode.includes("-tr") ||
              langCode.includes("-pl") || langCode.includes("-nl");

            if (!isAutoTranslated) {
              languages.push({
                code: langCode,
                name: langName,
                isAutoGenerated: currentSection === "auto"
              });
            }
          }
        }
      }

      languages.sort((a, b) => {
        if (a.isAutoGenerated !== b.isAutoGenerated) {
          return a.isAutoGenerated ? 1 : -1;
        }
        return a.name.localeCompare(b.name);
      });

      console.log(`[IPC] Found ${languages.length} available subtitle languages for ${videoID}`);
      return {languages};
    } catch (error) {
      console.error(`[IPC] Error getting YouTube subtitle languages for ${videoID}:`, error);
      return {languages: [], error: error.message};
    }
  });

  ipcMain.handle("downloadYoutubeSubtitle", async (event, videoID, lang) => {
    console.log(`[IPC] downloadYoutubeSubtitle called for ${videoID} (${lang})`);
    try {
      const ytDlpPath = await resolveToolCommand("yt-dlp");
      // A fresh folder per download: scanning the shared temp folder could pick up an older
      // file for the same video, or en-US when en was asked for.
      const tempDirPath = await fs.mkdtemp(path.join(os.tmpdir(), "miteiru_youtube_"));
      const outputBase = path.join(tempDirPath, `${videoID}_${lang}`);

      const extractArgs = [
        "--write-subs",
        "--write-auto-subs",
        "--sub-langs", lang,
        "--sub-format", "srt",
        "--skip-download",
        "--output", outputBase,
        `https://youtube.com/watch?v=${videoID}`
      ];

      console.log("[IPC] Running yt-dlp with args:", extractArgs);

      await new Promise<string>((resolve, reject) => {
        const child = spawn(ytDlpPath, extractArgs);
        let stdout = "";
        let stderr = "";

        child.stdout.on("data", (data) => {
          stdout += data.toString();
        });

        child.stderr.on("data", (data) => {
          stderr += data.toString();
        });

        child.on("close", (code) => {
          if (code === 0) {
            resolve(stdout + stderr);
          } else {
            reject(new Error(`yt-dlp failed with code ${code}: ${stderr}`));
          }
        });

        child.on("error", (err) => {
          reject(new Error(`Failed to spawn yt-dlp: ${err.message}`));
        });
      });

      const files = await fs.readdir(tempDirPath);
      const downloadedFile = files.find((file) => file.endsWith(".srt"));

      if (!downloadedFile) {
        console.log("[IPC] Available files:", files);
        throw new Error(`Could not find downloaded subtitle file for ${videoID} (${lang})`);
      }

      const actualFilePath = path.join(tempDirPath, downloadedFile);
      console.log(`[IPC] YouTube subtitle downloaded to: ${actualFilePath}`);

      return {
        success: true,
        filePath: actualFilePath,
        language: lang
      };
    } catch (error) {
      console.error(`[IPC] Error downloading YouTube subtitle for ${videoID} (${lang}):`, error);
      return {
        success: false,
        error: error.message
      };
    }
  });

  ipcMain.handle("getYoutubeSubtitle", async (event, videoID, lang) => {
    try {
      return await getSubtitles({
        videoID,
        lang
      });
    } catch (error) {
      console.error("Error fetching subtitles:", error);
      return [];
    }
  });

  ipcMain.handle("getYoutubeVideoTitle", async (_event, videoID: string) => {
    try {
      return await getYoutubeVideoTitle(videoID);
    } catch (error) {
      console.error(`[IPC] Error getting YouTube title for ${videoID}:`, error);
      return null;
    }
  });
}
