import {ipcMain} from "electron";
import {getSubtitles} from "../../helpers/getSubtitles";

export function registerYoutubeHandlers() {
  ipcMain.handle("getYoutubeSubtitleLanguages", async (event, videoID) => {
    console.log(`[IPC] getYoutubeSubtitleLanguages called for ${videoID}`);
    try {
      const {spawn} = require("child_process");
      const os = require("os");
      const path = require("path");
      const fs = require("fs/promises");

      const toolsDir = path.join(os.tmpdir(), "miteiru_tools");
      const executableName = process.platform === "win32" ? "yt-dlp.exe" : "yt-dlp";
      const internalPath = path.join(toolsDir, executableName);

      let ytDlpPath = "yt-dlp";
      try {
        await fs.access(internalPath);
        ytDlpPath = internalPath;
        console.log(`[IPC] Using internal yt-dlp: ${internalPath}`);
      } catch {
        console.log("[IPC] Using system yt-dlp");
      }

      const ytDlpOutput = await new Promise<string>((resolve, reject) => {
        const child = spawn(ytDlpPath, [
          "--list-subs",
          "--write-auto-subs",
          `https://youtube.com/watch?v=${videoID}`
        ]);

        let stdout = "";
        let stderr = "";

        child.stdout.on("data", (data) => {
          stdout += data.toString();
        });

        child.stderr.on("data", (data) => {
          stderr += data.toString();
        });

        child.on("close", (code) => {
          if (code === 0) {
            resolve(stdout + stderr);
          } else {
            reject(new Error(`yt-dlp failed with code ${code}: ${stderr}`));
          }
        });

        child.on("error", (err) => {
          reject(new Error(`Failed to spawn yt-dlp: ${err.message}`));
        });
      });

      interface SubtitleLanguage {
        code: string;
        name: string;
        isAutoGenerated: boolean;
      }

      const languages: SubtitleLanguage[] = [];
      const lines = ytDlpOutput.split("\n");
      let currentSection = null;

      const displayNames = new Intl.DisplayNames(["en"], {type: "language"});

      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        const trimmedLine = line.trim();

        if (trimmedLine.includes("Available subtitles for")) {
          currentSection = "manual";
          continue;
        } else if (trimmedLine.includes("Available automatic captions for")) {
          currentSection = "auto";
          continue;
        }

        if (trimmedLine.includes("Language") && trimmedLine.includes("Name")) {
          continue;
        }

        if (!trimmedLine || trimmedLine.startsWith("[")) {
          if (languages.length > 0 && trimmedLine.startsWith("[")) {
            break;
          }
          continue;
        }

        if (currentSection && trimmedLine) {
          const langMatch = trimmedLine.match(/^([a-z]{2}(-[A-Za-z]+)?)\s+(.+)/);
          if (langMatch) {
            const langCode = langMatch[1];
            const langName = displayNames.of(langCode) || langCode.toUpperCase();

            const isAutoTranslated = langCode.includes("-zh") || langCode.includes("-ja") ||
              langCode.includes("-ko") || langCode.includes("-ar") ||
              langCode.includes("-hi") || langCode.includes("-es") ||
              langCode.includes("-fr") || langCode.includes("-de") ||
              langCode.includes("-ru") || langCode.includes("-pt") ||
              langCode.includes("-it") || langCode.includes("-tr") ||
              langCode.includes("-pl") || langCode.includes("-nl");

            if (!isAutoTranslated) {
              languages.push({
                code: langCode,
                name: langName,
                isAutoGenerated: currentSection === "auto"
              });
            }
          }
        }
      }

      languages.sort((a, b) => {
        if (a.isAutoGenerated !== b.isAutoGenerated) {
          return a.isAutoGenerated ? 1 : -1;
        }
        return a.name.localeCompare(b.name);
      });

      console.log(`[IPC] Found ${languages.length} available subtitle languages for ${videoID}`);
      return {languages};
    } catch (error) {
      console.error(`[IPC] Error getting YouTube subtitle languages for ${videoID}:`, error);
      return {languages: [], error: error.message};
    }
  });

  ipcMain.handle("downloadYoutubeSubtitle", async (event, videoID, lang) => {
    console.log(`[IPC] downloadYoutubeSubtitle called for ${videoID} (${lang})`);
    try {
      const {spawn} = require("child_process");
      const tempDir = require("os").tmpdir();
      const tempFilePath = require("path").join(tempDir, `miteiru_youtube_${videoID}_${lang}_${Date.now()}.srt`);
      const os = require("os");
      const path = require("path");
      const fs = require("fs/promises");

      const toolsDir = path.join(os.tmpdir(), "miteiru_tools");
      const executableName = process.platform === "win32" ? "yt-dlp.exe" : "yt-dlp";
      const internalPath = path.join(toolsDir, executableName);

      let ytDlpPath = "yt-dlp";
      try {
        await fs.access(internalPath);
        ytDlpPath = internalPath;
        console.log(`[IPC] Using internal yt-dlp: ${internalPath}`);
      } catch {
        console.log("[IPC] Using system yt-dlp");
      }

      const extractArgs = [
        "--write-subs",
        "--write-auto-subs",
        "--sub-langs", lang,
        "--sub-format", "srt",
        "--skip-download",
        "--output", tempFilePath.replace(".srt", ""),
        `https://youtube.com/watch?v=${videoID}`
      ];

      console.log("[IPC] Running yt-dlp with args:", extractArgs);

      await new Promise<string>((resolve, reject) => {
        const child = spawn(ytDlpPath, extractArgs);
        let stdout = "";
        let stderr = "";

        child.stdout.on("data", (data) => {
          stdout += data.toString();
        });

        child.stderr.on("data", (data) => {
          stderr += data.toString();
        });

        child.on("close", (code) => {
          if (code === 0) {
            resolve(stdout + stderr);
          } else {
            reject(new Error(`yt-dlp failed with code ${code}: ${stderr}`));
          }
        });

        child.on("error", (err) => {
          reject(new Error(`Failed to spawn yt-dlp: ${err.message}`));
        });
      });

      const tempDirPath = path.dirname(tempFilePath);
      const files = await fs.readdir(tempDirPath);

      const downloadedFile = files.find(file =>
        file.includes(videoID) &&
        file.includes(lang) &&
        file.endsWith(".srt")
      );

      if (!downloadedFile) {
        console.log("[IPC] Available files:", files.filter(f => f.includes(videoID)));
        throw new Error(`Could not find downloaded subtitle file for ${videoID} (${lang})`);
      }

      const actualFilePath = path.join(tempDirPath, downloadedFile);
      console.log(`[IPC] YouTube subtitle downloaded to: ${actualFilePath}`);

      return {
        success: true,
        filePath: actualFilePath,
        language: lang
      };
    } catch (error) {
      console.error(`[IPC] Error downloading YouTube subtitle for ${videoID} (${lang}):`, error);
      return {
        success: false,
        error: error.message
      };
    }
  });

  ipcMain.handle("getYoutubeSubtitle", async (event, videoID, lang) => {
    try {
      return await getSubtitles({
        videoID,
        lang
      });
    } catch (error) {
      console.error("Error fetching subtitles:", error);
      return [];
    }
  });
}
