/**
 * @deprecated Import from `../UI` or `../UI/miteiruUiTheme` instead.
 * Re-exports preserve existing MeaningBox import paths.
 */
export {
  MEANING_SHELL,
  MEANING_HEADER,
  MEANING_BODY,
  MEANING_SECTION,
  MEANING_SECTION_LABEL,
  MEANING_SECTION_TITLE,
  MEANING_SECTION_HEADER,
  MEANING_ENTRY,
  MEANING_ENTRY_CHARACTER,
  MEANING_TAG_ROW,
  MEANING_TAG_ROW_CHARACTER,
  MEANING_TAG,
  MEANING_TAG_CHARACTER,
  MEANING_WORD_DISPLAY,
  MEANING_GLOSS,
  MEANING_GLOSS_INDEX,
  MEANING_ACTION_BTN,
  MEANING_KBD,
  MEANING_NOTE_LABEL,
  MEANING_NOTE_DIVIDER,
  MEANING_FIELD_INPUT,
  MEANING_READING_BUBBLE,
  MEANING_READING_BUBBLE_CHARACTER,
} from '../UI/miteiruUiTheme';
